Rails.application.routes.draw do
  get 'words/index'
  get 'words/show'
  get 'words/edit'
  get 'words/update'
  get 'words/new'
  get 'words/create'
  get 'words/destroy'
  get 'pictures/index'
  get 'pictures/show'
  get 'pictures/edit'
  get 'pictures/update'
  get 'pictures/new'
  get 'pictures/create'
  get 'pictures/destroy'
  get 'sentences/index'
  get 'sentences/show'
  get 'sentences/edit'
  get 'sentences/update'
  get 'sentences/new'
  get 'sentences/create'
  get 'sentences/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
